component: scf
name: slackbot-scf-timer
org: Tencent
app: wechatbot
stage: dev
inputs:
  src: ./src
  name: SF-bot
  runtime: Python3.6
  timeout: 30
  codeUri: ./SF-bot
  description: sends regular reminders
  region: ${env:REGION}
  environment:
    variables:
      url: ${env:WEBHOOK2}
      error_url: ${output:${stage}:${app}:getDeploymentErrorScf.triggers.apigw.0}
      #error_url: https://service-ea569l60-1302554812.gz.apigw.tencentcs.com/release/error_type
  handler: index.main_handler
  memorySize: 64
  tags:
    app: SF-bot
  events:
    - apigw:
        name: get_error_apigw
        parameters:
          protocols:
            - http
            - https
          serviceName: get_error
          description: get deployment error data
          environment: release
          endpoints:
            - path: /daily_errors
              method: ANY
              enableCORS: TRUE
              serviceTimeout: 10
    - timer:
         name: get_error_timer
         parameters:
           cronExpression: '0 59 23 * * * *'
           enable: true
           argument: argument
